List<String> charadesWordsEng = [
  'Airplane',
  'Boat',
  'Baby',
  'Ears',
  'Scissors',
  'Cough',
  'Cold',
  'Phone',
  'Laugh',
  'Blink',
  'Hairbrush',
  'Sneeze',
  'Spin',
  'Hammer',
  'Book',
  'Toothbrush',
  'Jump',
  'Clap',
  'Slap',
  'Archer',
  'Ghost',
  'Balance',
  'Shoelaces',
  'Sick',
  'Balloon',
  'Banana Peel',
  'Monster',
  'Hiccup',
  'Stomp',
  'Hurt',
  'Hungry',
  'Slip',
  'Karate',
  'Ladder',
  'Scare',
  'Fishing',
  'Dizzy',
  'Read',
  'Hot Birthday',
  'President',
  'Apartment',
  'Cradle',
  'Coffee',
  'Trampoline',
  'Waterfall',
  'Window',
  'Proud',
  'Stuck-up',
  'Flashlight',
  'Marry',
  'Overwhelm',
  'Judge',
  'Shadow',
  'Halo',
  'Measure',
  'Clown',
  'Chomp',
  'Slither',
  'Archery',
  'Basketball',
  'Figure Skating',
  'Hockey',
  'Baseball',
  'Croquet',
  'Golf',
  'Horseback Riding',
  'Cheerleading',
  'Football',
  'Soccer',
  'Darts',
  'Roller Derby',
  'Table Tennis',
  'Handball',
  'Whale',
  'Snake',
  'Elephant',
  'Giraffe',
  'Dog',
  'Cat',
  'Ant',
  'Rabbit',
  'Groundhog',
  'Hyena',
  'Kangaroo',
  'Shark',
  'Fish',
  'Polar Bear',
  'Caterpillar',
  'Cockroach',
  'Ram',
  'Monkey',
  'Jaguar',
  'Rooster',
  'Cycling',
  'Watching TV',
  'Swimming',
  'Running',
  'Flying in a plane',
  'Sleeping',
  'Flipping pancakes',
  'Listening to music',
  'Driving a car',
  'Writing a letter',
  'Skiing',
  'Giving a haircut',
  'Drinking',
  'Typing',
  'Eating',
  'Having a snowball fight',
  'Playing the guitar',
  'Surfing',
  'Yawning',
  'Playing golf',
  'Praying',
  'Brushing teeth',
  'Showering',
  'Meditating',
  'Singing',
  'Jump rope',
  'Using binoculars',
  'Barbie',
  'Elsa from Frozen',
  'Minecraft',
  'Ballerina',
  'Hula-hooping',
  'Fishing',
  'One of their parents',
  'Hopscotch',
  'Climbing monkey bars',
  'Ride a bike',
  'Riding in an airplane',
  'Sneezing',
  'Walking like a model',
  'Forgot keys',
  'Flirting',
  'Driving a car',
  'In a fight',
  'Walking a dog',
  'Going to bed',
  'Bored',
  'Grocery shopping',
  'Vacuuming',
  'Watering plants',
  'Making the bed',
  'Dusting',
  'Mopping',
  'Starting a fire in a fireplace',
  'Doing laundry',
  'Changing a light bulb',
  'Turning on a lamp',
  'Sad',
  'Angry',
  'Bitter',
  'Happy',
  'Excited',
  'Laughing',
  'Yelling',
  'Friendly',
  'Shy',
  'Scared',
  'Extroverted',
  'Introverted',
  'Mother',
  'Father',
  'Baby',
  'Toddler',
  'Brother',
  'Sister',
  'Grandparent',
  'Doctor',
  'Actress or actor',
  'Lawyer',
  'Librarian',
  'Social media influencer',
  'Cashier at store',
  'Waitress or waiter',
  'Chef',
  'Judge',
  'Crossing guard',
  'Car salesman',
  'Pastor',
  'Surgeon',
  'Lifeguard',
  'Lion tamer at a circus',
  'Writer',
  'Dentist',
  'Journalist',
  'Veterinarian',
  'Kangaroo',
  'Cat',
  'Frog',
  'Elephant',
  'Moose',
  'Bunny',
  'Wolf',
  'Snake',
  'Bird',
  'Camel',
  'Duck',

  // Add more words as needed
];

List<String> charadesWordsSwe = [
  'Flygplan',
  'Båt',
  'Bebis',
  'Öron',
  'Sax',
  'Hosta',
  'Förkylning',
  'Telefon',
  'Skratt',
  'Blinka',
  'Hårborste',
  'Nysning',
  'Snurra',
  'Hammare',
  'Bok',
  'Tandborste',
  'Hoppa',
  'Klappa',
  'Slå',
  'Bågskytt',
  'Spöke',
  'Balans',
  'Skosnören',
  'Sjuk',
  'Ballong',
  'Bananaskal',
  'Monster',
  'Hicka',
  'Stampa',
  'Skada',
  'Hungrig',
  'Halka',
  'Karate',
  'Stege',
  'Skrämma',
  'Fiske',
  'Yra',
  'Läs',
  'Hett födelsedag',
  'President',
  'Lägenhet',
  'Vagga',
  'Kaffe',
  'Trampolin',
  'Vattenfall',
  'Fönster',
  'Stolt',
  'Stygg',
  'Ficklampa',
  'Gifta sig',
  'Överväldiga',
  'Domare',
  'Skugga',
  'Halo',
  'Mäta',
  'Clown',
  'Tugga',
  'Slingra',
  'Bågskytte',
  'Basket',
  'Konståkning',
  'Hockey',
  'Baseboll',
  'Krocket',
  'Golf',
  'Ridning',
  'Cheerleading',
  'Fotboll',
  'Fotboll',
  'Dart',
  'Roller derby',
  'Bordtennis',
  'Handboll',
  'Val',
  'Orm',
  'Elefant',
  'Giraff',
  'Hund',
  'Katt',
  'Myra',
  'Kanin',
  'Murmeldjur',
  'Hyena',
  'Känguru',
  'Haj',
  'Fisk',
  'Isbjörn',
  'Fjäril',
  'Kackerlacka',
  'Vädur',
  'Apa',
  'Jaguar',
  'Tupp',
  'Cykling',
  'Titta på TV',
  'Simning',
  'Springa',
  'Flyga i ett flygplan',
  'Sova',
  'Steka pannkakor',
  'Lyssna på musik',
  'Köra bil',
  'Skriva ett brev',
  'Åka skidor',
  'Ge en klippning',
  'Dricka',
  'Skriva',
  'Äta',
  'Ha en snöbollskamp',
  'Spela gitarr',
  'Surfa',
  'Gäspa',
  'Spela golf',
  'Be',
  'Borsta tänderna',
  'Duscha',
  'Meditation',
  'Sjunga',
  'Hoppa rep',
  'Använda kikare',
  'Barbie',
  'Elsa från Frost',
  'Minecraft',
  'Ballerina',
  'Hula-hooping',
  'Fiske',
  'En av deras föräldrar',
  'Hoppa hopp',
  'Klättra på apstänger',
  'Cykla',
  'Åka flygplan',
  'Nysa',
  'Gå som en modell',
  'Glömt nycklarna',
  'Flörta',
  'Köra bil',
  'I ett slagsmål',
  'Promenera med en hund',
  'Gå och lägga sig',
  'Tråkig',
  'Handla mat',
  'Dammsugning',
  'Vattna växter',
  'Bädda sängen',
  'Damma',
  'Moppning',
  'Tända en eld i en öppen spis',
  'Tvätta kläder',
  'Byta glödlampa',
  'Tända en lampa',
  'Ledsen',
  'Arg',
  'Bitter',
  'Lycklig',
  'Uppspelt',
  'Skratta',
  'Skrika',
  'Vänlig',
  'Blyg',
  'Rädd',
  'Utåtriktad',
  'Introvert',
  'Mamma',
  'Pappa',
  'Bebis',
  'Småbarn',
  'Bror',
  'Syster',
  'Mormor/morfar',
  'Doktor',
  'Skådespelare eller skådespelerska',
  'Advokat',
  'Bibliotekarie',
  'Sociala medier-influencer',
  'Kassörska eller kassör',
  'Servitris eller servitör',
  'Kock',
  'Domare',
  'Skolövervakare',
  'Bilsäljare',
  'Pastor',
  'Kirurg',
  'Livräddare',
  'Lejontränare på cirkus',
  'Författare',
  'Tandläkare',
  'Journalist',
  'Veterinär',
  'Känguru',
  'Katt',
  'Groda',
  'Elefant',
  'Älg',
  'Kanin',
  'Varg',
  'Orm',
  'Fågel',
  'Kamel',
  'Anka',
  // Add more words as needed
];
