// truths.dart

List<String> truthsEng = [
  'What is your biggest fear?',
  'Share your most embarrassing experience.',
  'If you could have any superpower, what would it be and why?',
  'Have you ever faked being sick to get out of something?',
  'Who is your secret crush?',
  'What is your weirdest habit?',
  'Tell about a lie you have told that is still a secret.',
  'What is your favorite movie, and why do you love it?',
  'What is the weirdest dream you have ever had?',
  'If you could switch lives with someone for a day, who would it be?',
  'What is your most embarrassing childhood memory?',
  'What is the worst gift you have ever received?',
  'Have you ever tricked someone, and if so, how?',
  'What is your most embarrassing slip of the tongue?',
  'What is your secret talent?',
  'If you could be any famous person for a day, who would it be?',
  'What is your strangest habit?',
  'Have you ever been in love with your best friend\'s partner?',
  'What is your most embarrassing text message mistake?',
  'What is your weirdest dream job?',
  'Tell a secret you have never shared with anyone.',
  'What is your favorite dish, and can you cook it yourself?',
  'Have you ever skipped school or work without anyone knowing?',
  'What is the most childish thing you still do as an adult?',
  'Share your most embarrassing moment in front of a group of people.',
  'What is your weirdest fear?',
  'Have you ever cried during a movie? Which one?',
  'What is your guilty pleasure TV show?',
  'If you could only eat one type of food for the rest of your life, what would it be?',
  'What is the weirdest place you have ever slept?',
  'What is your most bizarre dream ever?',
  'Have you ever spied on someone?',
  'What is the weirdest thing you have ever bought?',
  'What is your biggest insecurity?',
  'What is your weirdest kitchen habit?',
  'What is the strangest food you have ever eaten?',
  'What is your oddest nickname?',
  "What is the most peculiar ringtone you've ever had?",
  'Have you ever eaten something directly from the packaging without cooking it?',
  'What is your most bizarre dream vacation destination?',
  'What is the weirdest compliment you have ever received?',
  'What is your most embarrassing loss in a game or competition?',
  'Have you ever gotten lost somewhere?',
  'What is your most absurd fear as an adult?',
  'What is the most childish thing you still do?',
  'What is your weirdest habit when stressed?',
];

List<String> daresEng = [
  'Do your best impression of a celebrity.',
  'Call a friend and sing "Happy Birthday" to them, no matter if it is their birthday or not.',
  'Send a silly selfie to the third person in your contact list.',
  'Speak in an accent for the next three rounds.',
  'Send a message to your crush confessing that you have a secret crush on them.',
  'Wear socks on your hands for the next three rounds.',
  'Post something embarrassing on your most used social media account.',
  'Go outside and shout "I love [your crush\'s name]" at the top of your lungs.',
  'Dance to a song chosen by the group for two minutes.',
  'Let the group choose a new nickname for you and use it for the rest of the game.',
  'Let someone else give you a makeover with items from the kitchen.',
  'Text your ex and tell them you miss them.',
  'Do a freestyle rap about a random object chosen by the group.',
  'Speak in an accent chosen by the group for the next three rounds.',
  'Send a text to your parents saying you have ran off.',
  'Put on a blindfold and attempt to draw something for the group to guess.',
  'Make a sandwich with ingredients chosen by the group.',
  'Act out a scene from your favorite movie without saying any words.',
  'Do your best impression of a cartoon character.',
  'Let the group take a funny photo of you to share on social media.',
  'Post a status on your social media confessing a fake secret.',
  'Speak only in rhymes for the next three rounds.',
  'Act like a specific animal chosen by the group for the next three rounds.',
  'Send a message to your crush saying you had a dream about them.',
  'Do a handstand for as long as you can.',
  'Call a friend and sing a love song to them.',
  'Let someone else choose a song for you to dance to.',
  'Text a friend and invite them to a fictional party at your house tonight.',
  'Create a funny, made-up story and tell it to the group.',
];

List<String> truthsSwe = [
  'Vad är din största rädsla?',
  'Dela med dig av ditt mest pinsamma upplevelse.',
  'Om du kunde ha vilken superkraft som helst, vilken skulle det vara och varför?',
  'Har du någonsin låtsats vara sjuk för att slippa något?',
  'Vem är din hemliga förälskelse?',
  'Vad är din konstigaste vana?',
  'Berätta om en lögn du har sagt som fortfarande är en hemlighet.',
  'Vad är din favoritfilm, och varför älskar du den?',
  'Vad är den konstigaste drömmen du någonsin haft?',
  'Om du kunde byta liv med någon för en dag, vem skulle det vara?',
  'Vad är ditt mest pinsamma barndomsminne?',
  'Vad är den sämsta present du någonsin har fått?',
  'Har du någonsin lurat någon, och i så fall, hur?',
  'Vad är din mest pinsamma felsägning?',
  'Vad är din hemliga talang?',
  'Om du kunde vara någon känd person för en dag, vem skulle det vara?',
  'Vad är din konstigaste vana?',
  'Har du någonsin varit förälskad i din bästa väns partner?',
  'Vad är ditt mest pinsamma textmeddelande-misstag?',
  'Vad är ditt konstigaste drömjobb?',
  'Berätta en hemlighet du aldrig har delat med någon.',
  'Vad är din favoriträtt, och kan du laga den själv?',
  'Har du någonsin skolkat från skolan eller jobbet utan att någon vet?',
  'Vad är det mest barnsliga du fortfarande gör som vuxen?',
  'Dela med dig av ditt mest pinsamma ögonblick inför en grupp människor.',
  'Vad är din konstigaste rädsla?',
  'Har du någonsin gråtit under en film? Vilken?',
  'Vad är din skyldiga nöjes-TV-serie?',
  'Om du bara kunde äta en typ av mat för resten av ditt liv, vad skulle det vara?',
  'Vad är det konstigaste stället du någonsin har sovit på?',
  'Vad är din mest bisarra dröm någonsin?',
  'Har du någonsin spionerat på någon?',
  'Vad är det konstigaste du någonsin har köpt?',
  'Vad är din största osäkerhet?',
  'Vad är din konstigaste kökshabit?',
  'Vad är den konstigaste mat du någonsin har ätit?',
  'Vad är ditt konstigaste smeknamn?',
  'Vad är den mest egendomliga ringsignal du någonsin har haft?',
  'Har du någonsin ätit något direkt från förpackningen utan att tillaga det?',
  'Vad är din mest bisarra drömsemesterdestination?',
  'Vad är det konstigaste komplimang du någonsin har fått?',
  'Vad är ditt mest pinsamma förlust i ett spel eller tävling?',
  'Har du någonsin gått vilse någonstans?',
  'Vad är din mest absurda rädsla som vuxen?',
  'Vad är det mest barnsliga du fortfarande gör?',
  'Vad är din konstigaste vana när du är stressad?',
];

List<String> daresSwe = [
  'Gör din bästa imitation av en kändis.',
  'Ring en vän och sjung "Ja må han leva" för dem, oavsett om det är deras födelsedag eller inte.',
  'Skicka en fånig selfie till tredje personen i din kontaktlista.',
  'Prata med brytning under de närmaste tre rundorna.',
  'Skicka ett meddelande till din förälskelse och erkänn att du har en hemlig förälskelse för dem.',
  'Bär strumpor på händerna de närmaste tre rundorna.',
  'Posta något pinsamt på ditt mest använda sociala mediekonto.',
  'Gå ut och skrik "Jag älskar [din crushs namn]" så högt du kan.',
  'Dansa till en låt vald av gruppen i två minuter.',
  'Låt gruppen välja ett nytt smeknamn åt dig och använd det resten av spelet.',
  'Låt någon annan göra om dig med saker från köket.',
  'Skicka ett meddelande till din ex och säg att du saknar dem.',
  'Gör en fristilrap om en slumpmässig sak vald av gruppen.',
  'Prata med brytning vald av gruppen under de närmaste tre rundorna.',
  'Skicka ett sms till dina föräldrar och säg att du har rymt.',
  'Sätt på dig en ögonbindel och försök att rita något för gruppen att gissa.',
  'Gör en smörgås med ingredienser valda av gruppen.',
  'Spela upp en scen från din favoritfilm utan att säga några ord.',
  'Gör din bästa imitation av en tecknad figur.',
  'Låt gruppen ta en rolig bild av dig att dela på sociala medier.',
  'Posta en status på dina sociala medier där du erkänner en falsk hemlighet.',
  'Prata endast i rim under de närmaste tre rundorna.',
  'Uppträd som ett specifikt djur valt av gruppen under de närmaste tre rundorna.',
  'Skicka ett meddelande till din förälskelse och säg att du har haft en dröm om dem.',
  'Gör en handstående så länge du kan.',
  'Ring en vän och sjung en kärlekssång för dem.',
  'Låt någon annan välja en låt för dig att dansa till.',
  'Skicka ett sms till en vän och bjud in dem till en påhittad fest hemma hos dig ikväll.',
];
